---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-api-db-url
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  refreshInterval: 15s

  target:
    name: auth-api-db-url

  dataFrom:
    - find:
        path: DB_
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: all-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-test

  refreshInterval: 15s

  target:
    name: all-secrets

  dataFrom:
    - find:
        name:
          regexp: .*
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiple-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  refreshInterval: 15s

  target:
    name: multiple-secrets

  data:
    - secretKey: DB_USER
      remoteRef:
        key: DB_USER
    - secretKey: DB_PASS
      remoteRef:
        key: DB_PASS
    - secretKey: DB_URL
      remoteRef:
        key: DB_URL
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-example
  namespace: default
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 15s
  secretStoreRefs:
    - name: doppler-auth-api
      kind: SecretStore
  selector:
    secret:
      name: foobar # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: FOO
        remoteRef:
          remoteKey: FOO
